import {describe, expect, it} from "vitest"
import {Interpolation, PPQN} from "@opendaw/lib-dsp"
import {TransientPlayMode} from "@opendaw/studio-enums"
import {createFixture, sample} from "./Fixture"

describe("Timeline", () => {
    it("creates note regions with defaults and events", () => {
        const {project} = createFixture()
        const track = project.addInstrumentUnit("Vaporisateur").noteTracks[0]
        const region = track.addRegion({position: PPQN.Bar, duration: PPQN.Bar * 2, label: "Verse"})
        expect(region.position).toBe(PPQN.Bar)
        expect(region.duration).toBe(PPQN.Bar * 2)
        expect(region.loopDuration).toBe(PPQN.Bar * 2)
        expect(region.loopOffset).toBe(0)
        expect(region.complete).toBe(PPQN.Bar * 3)
        expect(region.label).toBe("Verse")
        expect(region.hue).toBe(309)
        expect(region.track).toBe(track)
        expect(region.mute).toBe(false)
        const note = region.addEvent({position: 0, pitch: 64, duration: PPQN.Quarter, velocity: 0.5})
        expect(note.pitch).toBe(64)
        expect(note.velocity).toBe(0.5)
        expect(note.cents).toBe(0)
        expect(note.chance).toBe(100)
        expect(note.playCount).toBe(1)
        const defaults = region.addEvent()
        expect(defaults.position).toBe(0)
        expect(defaults.pitch).toBe(60)
        expect(defaults.duration).toBe(PPQN.SemiQuaver)
        expect(defaults.velocity).toBeCloseTo(100 / 127)
        region.addEvents([{position: PPQN.Quarter, pitch: 200}, {position: PPQN.Quarter * 2, pitch: -5}])
        expect(region.events.map(event => event.pitch)).toEqual([60, 64, 127, 0])
        note.pitch = 61.4
        expect(note.pitch).toBe(61)
        note.chance = 150
        expect(note.chance).toBe(100)
        note.cents = -80
        expect(note.cents).toBe(-50)
        expect(() => note.duration = 0).toThrow(RangeError)
        expect(() => region.addEvent({pitch: "C" as any})).toThrow(TypeError)
        expect(() => region.addEvent({bogus: 1} as any)).toThrow(TypeError)
        note.remove()
        expect(region.events.length).toBe(3)
        region.clearEvents()
        expect(region.events.length).toBe(0)
    })

    it("rejects overlapping regions and invalid durations", () => {
        const {project} = createFixture()
        const track = project.addInstrumentUnit("Vaporisateur").noteTracks[0]
        track.addRegion({position: 0, duration: PPQN.Bar})
        expect(() => track.addRegion({position: PPQN.Bar / 2, duration: PPQN.Bar})).toThrow(RangeError)
        expect(() => track.addRegion({position: PPQN.Bar, duration: 0})).toThrow(RangeError)
        expect(() => track.addRegion({position: PPQN.Bar, duration: -3})).toThrow(RangeError)
        const second = track.addRegion({position: PPQN.Bar, duration: PPQN.Bar})
        expect(track.regions.map(region => region.position)).toEqual([0, PPQN.Bar])
        second.position = 0
        expect(() => project.openInStudio()).toThrow(RangeError)
        second.position = PPQN.Bar * 4
        expect(() => project.openInStudio()).not.toThrow()
    })

    it("mirrors note regions and clips", () => {
        const {project} = createFixture()
        const track = project.addInstrumentUnit("Vaporisateur").noteTracks[0]
        const source = track.addRegion({duration: PPQN.Bar})
        source.addEvent({pitch: 70})
        const mirror = track.addRegion({position: PPQN.Bar, duration: PPQN.Bar, mirror: source})
        expect(mirror.events.map(event => event.pitch)).toEqual([70])
        mirror.addEvent({pitch: 72})
        expect(source.events.length).toBe(2)
        const clip = track.addClip({mirror: source, label: "Loop"})
        expect(clip.events.length).toBe(2)
        expect(clip.label).toBe("Loop")
        const valueTrack = project.output.addValueTrack(project.output, "volume")
        const valueRegion = valueTrack.addRegion()
        expect(() => track.addRegion({position: PPQN.Bar * 2, mirror: valueRegion as any})).toThrow(TypeError)
        source.remove()
        expect(mirror.events.length).toBe(2)
    })

    it("creates clips in free slots", () => {
        const {project} = createFixture()
        const track = project.addInstrumentUnit("Vaporisateur").noteTracks[0]
        const first = track.addClip()
        const third = track.addClip({index: 2, duration: PPQN.Bar * 2, mute: true, hue: 100, launch: {loop: false, speed: 2}})
        const second = track.addClip()
        expect([first.index, second.index, third.index]).toEqual([0, 1, 2])
        expect(track.clips.map(clip => clip.index)).toEqual([0, 1, 2])
        expect(third.duration).toBe(PPQN.Bar * 2)
        expect(third.mute).toBe(true)
        expect(third.hue).toBe(100)
        expect(third.launch.loop).toBe(false)
        expect(third.launch.speed).toBe(2)
        expect(first.launch.loop).toBe(true)
        expect(() => track.addClip({index: 1})).toThrow(RangeError)
        expect(() => {second.index = 2}).toThrow(RangeError)
        second.index = 5
        expect(second.index).toBe(5)
        expect(track.addClip().index).toBe(1)
        third.addEvent({pitch: 40})
        expect(third.events.length).toBe(1)
        expect(third.track).toBe(track)
        third.remove()
        expect(track.clips.length).toBe(3)
    })

    it("creates automation regions with ordered value events", () => {
        const {project} = createFixture()
        const unit = project.addInstrumentUnit("Vaporisateur")
        const track = unit.addValueTrack(unit.instrument, "cutoff")
        const region = track.addRegion({duration: PPQN.Bar * 4})
        expect(region.hue).toBe(158)
        const first = region.addEvent({position: PPQN.Bar, value: 0.8})
        const start = region.addEvent({position: 0, value: 0.2, interpolation: Interpolation.None})
        const step = region.addEvent({position: PPQN.Bar, value: 0.1})
        expect(region.events).toEqual([start, first, step])
        expect(first.interpolation).toEqual(Interpolation.Linear)
        expect(start.interpolation).toEqual(Interpolation.None)
        expect(() => region.addEvent({position: PPQN.Bar, value: 0.5})).toThrow(RangeError)
        first.value = 3
        expect(first.value).toBe(3)
        expect(() => first.value = NaN).toThrow(TypeError)
        first.interpolation = Interpolation.Curve(0.25)
        expect(first.interpolation.type).toBe("curve")
        first.interpolation = Interpolation.Linear
        expect(first.interpolation).toEqual(Interpolation.Linear)
        const clip = track.addClip()
        clip.addEvents([{position: 0, value: 0}, {position: PPQN.Bar, value: 1}])
        expect(clip.events.length).toBe(2)
        expect(track.regions.length).toBe(1)
        expect(track.clips.length).toBe(1)
        expect(() => track.addRegion({position: PPQN.Bar})).toThrow(RangeError)
    })

    it("creates audio regions in every playback mode", () => {
        const {project} = createFixture()
        const track = project.addInstrumentUnit("Tape").audioTracks[0]
        const loop = sample("Loop", 2.0, 120)
        const oneShot = sample("Hit", 0.5)
        const pitched = track.addRegion(loop)
        expect(pitched.playback).toBe("pitch")
        expect(pitched.duration).toBe(PPQN.Bar)
        expect(pitched.sample.uuid).toBe(loop.uuid)
        expect(pitched.sample.name).toBe("Loop")
        expect(pitched.label).toBe("Loop")
        expect(pitched.hue).toBe(187)
        expect(() => pitched.transpose = 3).toThrow(RangeError)
        expect(pitched.transpose).toBe(0)
        const noSync = track.addRegion(oneShot, {position: PPQN.Bar * 2})
        expect(noSync.playback).toBe("no-sync")
        expect(noSync.duration).toBe(0.5)
        const stretched = track.addRegion(loop, {position: PPQN.Bar * 4, playback: "timestretch", playbackRate: 0.5, transientPlayMode: TransientPlayMode.Once})
        expect(stretched.playback).toBe("timestretch")
        expect(stretched.playbackRate).toBe(0.5)
        expect(stretched.transientPlayMode).toBe(TransientPlayMode.Once)
        stretched.transientPlayMode = TransientPlayMode.Repeat
        expect(stretched.transientPlayMode).toBe(TransientPlayMode.Repeat)
        expect(() => stretched.transientPlayMode = 7 as TransientPlayMode).toThrow(RangeError)
        const spectral = track.addRegion(loop, {position: PPQN.Bar * 6, playback: "signalsmith", transpose: 5, gain: -3, fading: {in: 100, out: 200}})
        expect(spectral.playback).toBe("signalsmith")
        expect(spectral.transpose).toBe(5)
        expect(spectral.gain).toBe(-3)
        expect(spectral.fading.in).toBe(100)
        expect(spectral.fading.out).toBe(200)
        expect(spectral.fading.inSlope).toBeCloseTo(0.75)
        spectral.transpose = 40
        expect(spectral.transpose).toBe(24)
        expect(() => track.addRegion(loop, {playback: "warp" as any})).toThrow(RangeError)
        expect(() => track.addRegion({uuid: "nope", name: "x", duration: 1, bpm: 0, sample_rate: 1})).toThrow(TypeError)
        expect(() => track.addRegion(sample("Empty", 0))).toThrow(RangeError)
        expect(track.regions.map(region => region.playback)).toEqual(["pitch", "no-sync", "timestretch", "signalsmith"])
        const clip = track.addClip(loop, {playback: "timestretch", launch: {reverse: true}})
        expect(clip.playback).toBe("timestretch")
        expect(clip.launch.reverse).toBe(true)
        expect(clip.duration).toBe(PPQN.Bar)
        const rawClip = track.addClip(oneShot)
        expect(rawClip.playback).toBe("no-sync")
        expect(rawClip.index).toBe(1)
        expect(() => project.addInstrumentUnit("Vaporisateur").noteTracks[0].addRegion({duration: 1} as any)).not.toThrow()
        expect(() => (track as any).addRegion(undefined)).toThrow(TypeError)
    })

    it("refuses content on mismatched tracks", () => {
        const {project} = createFixture()
        const unit = project.addInstrumentUnit("Vaporisateur")
        const noteTrack = unit.noteTracks[0]
        const audioTrack = unit.addAudioTrack()
        expect(() => (audioTrack as any).addRegion({duration: 1})).toThrow()
        expect(() => (noteTrack as any).addRegion(sample())).toThrow()
    })

    it("removes tracks with their content", () => {
        const {project} = createFixture()
        const unit = project.addInstrumentUnit("Vaporisateur")
        const track = unit.noteTracks[0]
        const region = track.addRegion()
        const note = region.addEvent()
        track.remove()
        expect(unit.tracks.length).toBe(0)
        expect(() => region.position).toThrow()
        expect(() => note.pitch).toThrow()
        expect(() => track.addRegion()).toThrow()
    })
})
